# Generated by Django 6.0.3 on 2026-04-03 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('ultimish_word', models.CharField(max_length=100)),
                ('english_translation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TableGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new', 'New'), ('edit', 'Edit')], max_length=10)),
                ('ultimish_word', models.CharField(max_length=100)),
                ('suggested_translation', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('target_word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.mainword')),
            ],
        ),
        migrations.AddField(
            model_name='mainword',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.tablegroup'),
        ),
    ]
